### ISSUE TITLE
Question: what are the business rules to follow in order to make a charge?

### ISSUE THREAD

**Issue by robertomiranda** [ride-interviews/backend-roberto-miranda#1]

**Comment by buritica** [comment]
Everyone should be charged a fixed fee of $1.00 per ride.

**Comment by robertomiranda** [comment]
@buritica  when you say everyone means the riders? the company is no charged for anything?

**Comment by buritica** [comment]
yes, only riders. assume the company has no charges because we may have some deals with them in place later, they could give subsidies perhaps, but not at this moment.
